### PR TITLE
Fix bugs on error.ftl template

### PR DESCRIPTION
**Pull request by Ann2827**
Hi.
This time I checked the `error.ftl` template in an unusual way. Open login form -> click on form "view the element code" -> change `<form id="kc-form-login" action="https://my.domain.com/auth/realms/admitad/login-actions/authenticate?session_code=5CiEGX...` to `<form id="kc-form-login" action="https://my.domain.com/auth/realms/admitad/login-actions/123?session_code=5CiEGX...` -> click "log in" (you can not to fill in the fields). This is a quick way to open error form.
The form will open when using the base theme but not a custom theme.
The problem lies in the three recursive keys:
- .data_model.realm.masterAdminClient.realm...
- .data_model.realm.delegateForUpdate.masterAdminClient.realm...
- .data_model.realm.defaultRole.container.masterAdminClient.realm...

I also found that key `messagesPerField` doesn`t exists on this template. (This does not break the form, but it is visible in the logs)

### CODE REVIEW

**Comment by garronej** [comment]
Very nice!  
Thank you for your contribution @Ann2827 !

**Comment by loki344** [comment]
Hi @garronej and @Ann2827 
When entering the error page we encounter the following log:


2022-08-04 07:32:29,846 ERROR [freemarker.runtime] (executor-thread-23) Error executing FreeMarker template part in the #attempt block: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> messagesPerField  [in template "error.ftl" at line 85, column 37]
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----
----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if messagesPerField.exists("${fieldN...  [in template "error.ftl" at line 85, column 32]
----
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85)
	at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:48)
	at freemarker.core.NonHashException.<init>(NonHashException.java:49)
	at freemarker.core.Dot._eval(Dot.java:48)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalToBoolean(Expression.java:177)
	at freemarker.core.Expression.evalToBoolean(Expression.java:163)
	at freemarker.core.IfBlock.accept(IfBlock.java:49)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.visitAttemptRecover(Environment.java:564)
	at freemarker.core.AttemptBlock.accept(AttemptBlock.java:45)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at freemarker.template.Template.process(Template.java:383)
	at org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:68)
	at org.keycloak.services.error.KeycloakErrorHandler.getResponse(KeycloakErrorHandler.java:95)
	at org.keycloak.services.error.KeycloakErrorHandler.toResponse(KeycloakErrorHandler.java:56)
	at org.jboss.resteasy.core.ExceptionHandler.executeExceptionMapper(ExceptionHandler.java:136)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:309)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)



Looking at the generated error.ftl from keycloakify I don't quite understand why we end up in this situation:

image


Did you guys encounter anything like this?

**Comment by loki344** [comment]
Actually, the error log is a lot bigger. It happens after a NullPointer in Keycloak (which is unrelated to Keycloakify) and keycloak tries to display the error.ftl:
[error_log.txt](https://github.com/InseeFrLab/keycloakify/files/9257663/error_log.txt)

**Comment by garronej** [comment]
@loki344 thanks for reporting.  
Maybe the error is related with those custom fields I temporarely added to accomodate a user:  
https://github.com/InseeFrLab/keycloakify/issues/40#issuecomment-1202079564  

https://github.com/InseeFrLab/keycloakify/commit/18a2e4ae0429dcf5c94d2ba125f4896c59e13b38

Do you get the same error if you remove them?

**Comment by loki344** [comment]
@garronej I would remove them, but I am the user you accommodated with those extra fields. But I guess i'll stick around until v6 comes out and see how things work out with the new declarations of fields 😉

**Comment by garronej** [comment]
@loki344 ohhh sorry, I didn't connect the dots.  
I only have one hour a day for OSS maintenance work.  

So I guess that what is happening is that you do need your extra fields on `register.ftl`, `login.ftl` and maybe some other pages (?) but when Keycloakify tries to read them from `error.ftl` your adapter throws a null pointer exception.  

The problem is that, even if the exception is cought in the .ftl code generated by Keycloakify, the error still ends up in the log.  It's very anoying but there is no way to prevent this.  

I see two option here. 
- First (not the best) is to make sure that your adapter never throws, no matter what. This should more like a hack to me.  
- Second is for me to allow, in v6, to specify on which page the extra field should be available with a syntax like:   
`package.json`
```typescript
    "keycloakify": {
        "extraFields": {
               "register.ftl": [
                 "user.attributes.dateOfBirth", 
                 "user.attributes.country", 
                 "user.attributes.acceptedTermsAndConditions" 
               ]
         }
    },
```

What do you think?

**Pull request merged**
