### PR TITLE
Prevent ftl errors in Keycloak log

### PR DESCRIPTION
**Pull request by garronej**
Follow-up of #63 

This PR publishes [beta releases](https://www.npmjs.com/package/keycloakify/v/4.2.14-beta.0). 

It won't make it into [main](https://github.com/InseeFrLab/keycloakify) until [this](https://github.com/InseeFrLab/keycloakify/pull/63%23issuecomment-988911574) is achieved.  

If you want to contribute, thank you and submit your PRs to the branch [doge_ftl_errors](https://github.com/InseeFrLab/keycloakify/tree/doge_ftl_errors) rather than to [main](https://github.com/InseeFrLab/keycloakify).

### CODE REVIEW

**Comment by marziman** [comment]
Thanks @garronej you are awesome mate!

**Comment by marziman** [comment]
@garronej after applying the beta version 
we had many places to be changed, which we wanted to avoid. Actually it even broke some things.

This is a piece of our package.json dependencies:

`"dependencies": {
        "@chakra-ui/react": "latest",
        "@emotion/react": "^11.4.1",
        "@emotion/styled": "^11",
        "framer-motion": "^4",
        "keycloakify": "latest",
        "node-sass": "",
        "react": "^17",
        "react-dom": "^17",
        "react-password-strength-bar": "latest",
        "tss-react": "^0.0.12",
        "web-vitals": "^2.1.0"
    },
    "devDependencies": {
        "@testing-library/jest-dom": "^5",
        "@testing-library/react": "^11",
        "@testing-library/user-event": "^12",
        "@types/jest": "latest",
        "@types/node": "latest",
        "@types/react": "latest",
        "@types/react-dom": "^17",
        "react-scripts": "latest",
        "typescript": "^4"
    },`
    
   We are a bit behind the new Keycloakify. Do you think there is a chance we can prevent the ftl changes or get a version, without the need to migrate our current keycloakify based project and UIs?
   
  I suspect the beta version you generated is based on 4.2.14 and we are on latest (4.2.13)?

**Comment by garronej** [comment]
Hi @marziman,  

There is almost no breaking changes between v2 and v4.

You need to install the peer dependencies required:  `yarn add keycloakify @emotion/react tss-react powerhooks`
Install `powerhooks` and update `tss-react` to the current version. You are locked on `v0.X.X`.  

There is also [`useKcMessages`](https://github.com/InseeFrLab/keycloakify#v4) that is a bit different.  

And finally if you have some missing pages in your [`KcApp.tsx`](https://github.com/garronej/keycloakify-demo-app/blob/look_and_feel/src/KcApp/KcApp.tsx) that are new and you don't have, add them.  

If you want up to date examples you have the two template repos and [the code](https://github.com/InseeFrLab/onyxia-web/tree/main/src/app/components/KcApp) of the login of [our platform](https://datalab.sspcloud.fr).

> Do you think there is a chance we can prevent the ftl changes or get a version, without the need to migrate our current keycloakify  

You are asking for custom work that doesn't benefit the open-source community here. So ok but my rate is 100€/hour.

**Comment by marziman** [comment]
No actually I am not asking for custom work :-) We can do that our own.
I just did not expect that there is changes to be done, if the Keycloakify generator is modified to be relaxed on errors.
If there are changes to be done, than this is breaking. What I asked was a backport of supressing errors, which are spamming the logs and slowing the whole Keycloak down. I am not sure what is custom on that.

I did the things above but had several errors. I will give it another try.
Also I could just pick the changes and apply them myself.

> You are asking for custom work that doesn't benefit the open-source community here. So ok but my rate is 100€/hour.

Every discussion here benefits the OSS community and especially Keycloakify. I am not sure how you come to these conclusions. When someone had issues with their versions of forks, I always help them. Maybe you have a differen view on OSS maintainership and must be getting much requests here (which I can not see form issues, compared to the amount of issues of other projects).

Still thank you for you answer.
BR Mehmet

**Comment by garronej** [comment]
Sorry giving you my rate was maybe a bit harsh but understand me.  
I took time to give you a detailed answer about fonts, I updated the template repo to make it easily understandable.  
I also published this beta release for you so you can benefit from @Ann2827 work before its production ready.  
And now, forgive me if I miss-understood, but I thought you were asking me to publish a version of Keycloakify that would be retrocompatible with v2 that would also incorporate @Ann2827 fixes so you don’t have to update...   

Don't get me wrong I love answering questions and feedback help me prioritize features. But sometimes I feel are asking a bit too much of me.

**Comment by marziman** [comment]
He @garronej no worries, I understand. People many times ask questions and also expect that a maintainer half works for him :-) But I am not that type. I made it work and "ported" it back to the v2. In KC 15.0.0 Errors are gone and I will observe that a bit more. In this way I will do a bit beta tester for the error logs fixing. If that works smooth for v2 than it shall make big issues for v4.

So far it looks good. I am eager to report back and will let it run for some while to see its behaviour.

BR Mehmet

**Comment by garronej** [comment]
Ok thank you for your understanding.  
I will delete the drama if you'll allow me. First because I wish I didn't overreact. Second because I want to suppress off topic discussion.

**Comment by marziman** [comment]
Of course. Lets clean up here :-) I will remove some things...

**Comment by Ann2827** [comment]
@garronej Hi! In the meantime, I tried to sort through the object only by known keys. It works. But it looks like over engineering. [ftl template](https://github.com/Ann2827/freemarker-templates/blob/main/parse-object.ftl) Some types are missing in the search. But I'll probably stop developing this idea.

**Comment by garronej** [comment]
Hello @Ann2827 thanks for your effort.  
[I rewrote the whole thing yesterday](https://github.com/InseeFrLab/keycloakify/tree/doge_ftl_errors/src/bin/build-keycloak-theme/generateFtl). It now works fast and without logging errors, it prints out well-formatted JS and it's much better FreeMarker code overall🍾
image
   
The big breakthrough was the realization that using `foo.bar??` we can test if a property is dereferencable without throwing if it isn't.  
I only tested with `login.ftl` but there are still some properties that throw when dereferenced.  
Namely `url. loginUpdatePasswordUrl`, `url. loginUpdateProfileUrl`, `url.loginUsernameReminderUrl` and `url.loginUpdateTotpUrl`.
I did what I suggested about them, I implemented [a blacklist](https://github.com/InseeFrLab/keycloakify/blob/484f95f5d2bea5fd756d1698d4aa0bcf0eb4adf4/src/bin/build-keycloak-theme/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#L114-L120) so that these properties can be skipped.  I allowed myself to do that because [it's never used](https://github.com/keycloak/keycloak/search?q=loginUpdatePasswordUrl) in the base theme but I suspect it won’t throw in all conditions, sometimes these value might be needed.  
I would like to avoid logging error as much as possible but I'd rather log inconsequential error that potentially preventing some use case from being implemented. I am going to see with the Keycloak team about that.

**Comment by garronej** [comment]
@Ann2827 [A new beta](https://www.npmjs.com/package/keycloakify/v/4.2.14-beta.1) have been released if you want to try it out.

**Comment by Ann2827** [comment]
@garronej 

I will definitely try the new version tomorrow.
On `register.ftl` template, you may encounter a problem with `auth.attemptedUsername `. And this is already bad. If keys: `loginUpdatePasswordUrl `, `loginUpdateProfileUrl `, `loginUsernameReminderUrl ` and `loginUpdateTotpUrl ` are not used anywhere, then key `attemptedUsername` is used on `login-reset-password.ftl` template. But if you try to get the value by key `auth.attemptedUsername ` on `login.ftl` and `login-reset-password.ftl` templates  (I didn't check the other templates), then you won't get an error.

On `login-update-profile` template, you may encounter a problem with `updateProfileCtx` object. And for `saml-post-form.ftl` template it will be an error to get the value by key `url.loginAction`.

Perhaps Keycloak will be able to return only those values that Freemarker templates will be able to read without errors? For example null. FreeMarker can check `foo.bar??` or `foo.bar!""` if the value cannot be obtained. But FreeMarker can't read `extended_hash+string`.

**Comment by garronej** [comment]
@Ann2827 Thank you for your investigation! I added special cases for [the cases you mentioned](https://github.com/InseeFrLab/keycloakify/blob/a8623d80661e5f5163f10536c4b73e6686bb5ecd/src/bin/build-keycloak-theme/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#L117-L145).  
I will create special cases like this whenever a new ftl error is reported to me.  

I will merge this now a publish a new release.

**Comment by garronej** [comment]
[4.2.14](https://www.npmjs.com/package/keycloakify/v/4.2.14) is out.

**Pull request merged**
